# Generated by Django 5.0.3 on 2024-04-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_options_alter_bookinstance_options_and_more'),
        ('catalog', '0025_auto_20220222_0623'),
    ]

    operations = [
    ]
